### ISSUE TITLE
【问题】端口扫描不完整

### ISSUE THREAD

**Issue by Zhang21** [5wimming/ASE#1]
比如我的机器开放了80,443,8000-8010。

第一次扫描到了443,8001,8009，再次扫描又扫描到了443,8000-8010，再次扫描又扫到了80端口。

请问这是masscan的问题么？和设置的线程数，端口数量，masscan --rate有关系吗？

**Comment by 5wimming** [comment]
是masscan的问题，一开始全程用nmap，ip和端口一多，奇慢无比，所以才采用masscan+nmap形式，周末我把masscan参数再优化一下

**Comment by 5wimming** [comment]
应该好了，可以再试试

**Comment by Zhang21** [comment]
好的，谢谢。

**Comment by Zhang21** [comment]
好像效果确实要好一些了，谢谢作者。
